In [1]:
x = 10
y = 20
print(x * y)

200


In [2]:
z = 30

In [3]:
x + y + z

60

In [4]:
import numpy as np

array1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
array2 = np.array([[9,8,7],
                   [6,5,4],
                   [3,2,1]])

array1 * array2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [5]:
5 - array1

array([[ 4,  3,  2],
       [ 1,  0, -1],
       [-2, -3, -4]])

In [6]:
array3 = np.arange(10)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array4 = np.zeros((4,3), np.int32)
array4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [14]:
array5 = np.random.rand(3,3)
array5

array([[0.68264192, 0.17118276, 0.30976616],
       [0.16913165, 0.17848313, 0.26409094],
       [0.22566511, 0.98109739, 0.76442046]])

In [15]:
array6 = np.arange(0,180,10).reshape(2,3,3)
array6

array([[[  0,  10,  20],
        [ 30,  40,  50],
        [ 60,  70,  80]],

       [[ 90, 100, 110],
        [120, 130, 140],
        [150, 160, 170]]])

In [16]:
array6 < 100

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True, False, False],
        [False, False, False],
        [False, False, False]]])

In [17]:
np.get_printoptions()# 省略しないで表示する数の設定などが行える

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}